lunarmodules/luasql

- src/ls_mysql.c
I made some minor changes to ls_mysql.c to make it work with lua 5.3. I have been using this for some time now, so I am confident that it is all that needs to be done to achieve compatibility with lua 5.3, without breaking backwards compatibility with 5.2 and 5.1.
> changes for lua 5.3 compatibility

- tests/odbc.lua
Fixed typo in DROP_TABLE_RETURN_VALUE variable name in assert2 statement on line 30.
> tests/odbc.lua - fixed typo in variable name

- src/ls_firebird.c
Fixes build failure on e.g. FreeBSD
> Use <stdlib.h> instead of deprecated <malloc.h>

- src/ls_postgres.c
Per #45 and dac9faf47c4eb2e47f1e64eb0d98ce37016b7d4d (comment inline)
Avoid a Valgrind invalid read from a stale PGconn pointer.
> Call PQfinish after PQerrorMessage when connection fails

- src/ls_mysql.c
From recent master:
$ make mysql
[...snip...]
src/ls_mysql.c: In function `cur_nullify':
src/ls_mysql.c:193: warning: control reaches end of non-void function
$
s/int/void/ to match function prototype in other database connectors
> silence a compiler warning in src/ls_mysql.c

- src/ls_mysql.c
fixing issue #22.
I see that there is no either mysql_library_end or mysql_server_end that should free resource handler allocated by mysql_init
That is why when use library with Apache that fork child and keep child alive reusing library at lua scripts cause leak of thread handlers and error
LuaSQL: error connecting: Out of memory.
along with libmysqlclient library error
Can't initialize threads: error 11
and following stack obtained with strace
libmysqlclient.so(my_thread_global_init
libmysqlclient.so(my_init
libmysqlclient.so(mysql_server_init
libmysqlclient.so(mysql_init
mysql.so(env_connect
luajit(luaL_openlibs
> fixing leak of mysql thread handlers

- src/ls_sqlite3.c
This isn't documented well @ http://www.sqlite.org/inmemorydb.html since sqlite3_open() is obsolete.
SQLITE_OPEN_CREATE flag avoids the usage of pure memory databases. If this flag is set a db file is created and referenced.
SQLITE_OPEN_MEMORY flag works as expected.
Is there any info about line 577? I would like to add an argument for all possible flags (see sqlite3.h 'Flags For File Open Operations') but args 4 doesn't seem to be future-proof.
> fix memory db connection creating and using file based db

- rockspec/luasql-mysql-2.3.4-1.rockspec
- rockspec/luasql-oci8-2.3.4-1.rockspec
- rockspec/luasql-odbc-2.3.4-1.rockspec
- rockspec/luasql-sqlite-2.3.4-1.rockspec
- rockspec/luasql-sqlite3-2.3.4-1.rockspec
Since version 2.3.4 was tagged in the source code, it's better to release matching rockspecs for all drivers to avoid confusion, and make the latest code more widely available. This also solves long standing compatibility issues.
Closes #6. (Lua 5.2 compatibility for odbc)
Closes #30. (Lua 5.3 support for luasql-mysql)
(And it possibly closes more issues as well!)
Please upload these rockspecs to luarocks.org after merging using `luarocks upload <file.rockspec>`, so that the .src.rock files get generated and uploaded as well. Thank you!
> Rockspecs for version 2.3.4

- src/ls_oci8.c
Dear author.
I use a very old version Oracle database. The version of Oracle is 10.2.0.4.
When I use a courser to fetch data from the database in remote with different charset, the error occurs.
I find that the server does not return the correct length of VARCHAR2, so I add some ugly codes to fix this problem.
Thank you very much.
> fix Oracle ORA-01406 in 10.0.2.4

- src/ls_firebird.c
- tests/firebird.lua
Things such as:
* `INSERT INTO ... RETURNING SomeCol1, SomeCol2`
* `EXECUTE BLOCK ... RETURNS ...`
* `EXECUTE PROCEDURE ... RETURNING ...`
Currently Firebird only supports returning one row from such actions.
> Added support for handling Procedures and Returning SQL

- src/ls_odbc.c
This fixes a bug that I'm currently experiencing reproducible in the following way:
- Use lua5.3
- `sizeof(long int)` must be 8
- `sizeof(SQLINTEGER)` must be 4
- Select some integer values
Selecting a column of integer type would mess up the values.
Current behavior:
4 is the "got" size, the mess of numbers is the returned value.
Updated behavior:
4 is still the "got" size, the value "2247" is correctly returned.
> Fix ODBC types to match standard typedefs

- doc/br/manual.html
- doc/fr/manual.html
- doc/us/manual.html
- src/ls_sqlite3.c
Add an option in env:connect in sqlite3 to allow users to connect to the
DB in read only mode.
We use luasql in our code base and have found that it is better to open up a database in readOnlyMode when reading the DB if multiple modules are accessing the database for reads and writes.
> Add an option to env:connect in sqlite3

- src/ls_odbc.c
Add support for e.g. SQL Server "uniqueidentifier" data types to be returned as a GUID string for ODBC.
> Support for returning ODBC "SQL_GUID" as string

- config
For our packaging efforts at openSUSE we need to set standard variables like CFLAGS to our standard value (mainly for security and performance reasons).
> Allow influencing CFLAGS from the external environmental variable.

- rockspec/luasql-odbc-2.6.0-3.rockspec
added `platforms` switch for both windows and unix. Links `odbc32` to Windows and `odbc` to Unix.
Tested on Windows 10 and Ubuntu 20.04 (WSL version)
> fixing build for luasql-odbc on Windows platforms

- src/ls_sqlite3.c
The `lua_isinteger` function is only present in Lua 5.3+. To maintain compatibility with earlier Lua versions (notably 5.2 and 5.1) this pull request gates the usage of this function with `defined` pre-processor checks. In the case where the symbol is not defined, we unconditionally fall back to existing logic that treats the maybe-an-int item in question as if `lua_isinteger` returned false.
Resolves https://github.com/lunarmodules/luasql/issues/147
> ls_sqlite3: conditional use of lua_isinteger

- src/ls_firebird.c
- src/ls_mysql.c
- src/ls_oci8.c
- src/ls_odbc.c
- src/ls_postgres.c
- src/ls_sqlite.c
- src/ls_sqlite3.c
- src/luasql.h
This pull request addresses the incompatibilities introduced in Lua 5.4, where `lua_newuserdata` was replaced by `lua_newuserdatauv`
- Introduced `LUASQL_NEWUD` macro to abstract the differences between `lua_newuserdata` and `lua_newuserdatauv`. 
This change improves code readability and reduces redundancy by centralizing the version check and userdata creation logic.
- Updated all drivers to use the `LUASQL_NEWUD` macro for consistent and version-agnostic userdata creation.
> Fix Lua 5.4 incompatibilities by adding `LUASQL_NEWUD` macro for User data Creation

- src/ls_firebird.c
- src/ls_mysql.c
- src/ls_oci8.c
- src/ls_odbc.c
- src/ls_postgres.c
- src/ls_sqlite.c
- src/ls_sqlite3.c
- tests/test.lua
- tests/to_be_closed_support.lua
This pull request addresses the Adaptation of LuaSQL drivers to `to-be-closed` variables introduced in Lua 5.4 
- Added `__close` metamethod to `cursor`, `connection` and `environment` objects of drivers to make them compatible to to-be-closed variation of objects 
- Added Test Suite to test `to-be-closed support` of LuaSQL Drivers
- Added Correction on compilation messages
> Driver Adaptation to `To-be-Closed` variables and Enhancement of Test Suite 

- src/ls_oci8.c
It is now possible to directly query DATE and TIMESTAMP data types.
There is no direct support for these types in the original OCI interface version 8, so the code is guarded by ifdef checks.
Unfortunately, there is no interface to query the buffer size required for output strings. In order not to overcomplicate the code, a conservative size of 65 bytes (including NUL) was chosen. The "fsprec" parameter is not specified clearly, so a value of "6" was chosen for microsecond precision.
The code was compiled using a current [Oracle Instant Client SDK](https://www.oracle.com/database/technologies/instant-client/downloads.html) on Arch Linux using Lua 5.4.
Tests were performed by starting a [container](https://hub.docker.com/r/gvenzl/oracle-xe) using `podman` and running the following Lua …
> Implement dates and timestamps in OCI driver

- src/ls_odbc.c
> odbc: Fallback to string for unknown sql types

- src/ls_odbc.c
When `UNICODE` is defined, SQL* functions are mapped to -W functions which require `wchar_t` input. Define `SQL_NOUNICODEMAP` to disable the mapping.
> odbc: Fix build when UNICODE is defined
